export const FLM1_REPORTS_SETTING_CATEGORY = "REPORTS";
export const FLM1_CURRENCY_COLUMN_COUNT_CODE = "FLM1_CURRENCY_COLUMN_COUNT";
export const FLM1_DEFAULT_CURRENCY_COLUMNS = 5;
export const FLM1_MIN_CURRENCY_COLUMNS = 1;
export const FLM1_MAX_CURRENCY_COLUMNS = 12;
export const FLM1_DEFAULT_PRODUCT_CODE = "CN";
