export enum CategoryOptionCodeEnum {
  LocationType = "LOCATIONTYPE",
  RiskCategory = "RISKCATEGORY",
  FinancialType = "FINANCIALTYPE",
  DefaultSign = "DEFAULTSIGN",
  DivisionDept = "DIVISIONDEPT",
  AccountType = "ACCOUNTTYPE",
  SubLedger = "SUBLEDGER",
  BankNature = "BANKNATURE",
  KycRiskCategory = "KYCRISKCATEGORY",
  EntityType = "ENTITYTYPE",
  DefaultAgent = "DEFAULTAGENT",
  Group = "GROUP",
  DocumentGroup = "DOCUMENTGROUP",
  MarketingExecutive = "MARKETINGEXECUTIVE",
  BusinessNature = "BUSINESSNATURE",
  TdsGroup = "TDSGROUP",
  MasterDocument = "MASTER",
  TransactionDocument = "TRANSACTION",
}
