export enum CategoryOptionCodeEnum {
  LocationType = "locationType",
  RiskCategory = "riskCategory",
  FinancialType = "financialType",
  DefaultSign = "defaultSign",
  DivisionDept = "divisionDept",
  AccountType = "accountType",
  SubLedger = "subLedger",
  BankNature = "bankNature",
  KycRiskCategory = "kycRiskCategory",
  EntityType = "entityType",
  DefaultAgent = "defaultAgent",
  Group = "group",
  MarketingExecutive = "marketingExecutive",
  BusinessNature = "businessNature",
  TdsGroup = "tdsGroup",
}
